### ISSUE TITLE
nama file berubah

### ISSUE THREAD

**Issue by adityakurnias** [adeleeeeyyyy/web-downloader#3]
tolong admin buat agar nama file sama seperti judul video youtubenya

**Comment by adeleeeeyyyy** [comment]
@app.route('/download', methods=['POST'])
def download_video():
    url = request.form['url']
    format = request.form['format']
    resolution = request.form['resolution']
    
    yt = YouTube(url)
    title = yt.title
    stream = yt.streams.filter(res=resolution).first()
    if format == 'mp4':
        file_extension = '.' + stream.mime_type.split('/')[1]
    else:
        stream = yt.streams.filter(only_audio=True).first()
        file_extension = '.mp3'
    
    output_file = stream.download(filename=title)
    base, ext = os.path.splitext(output_file)
    new_file = base + file_extension
    os.rename(output_file, new_file)
    
    return send_file(new_file, as_attachment=True)

**Comment by adityakurnias** [comment]
mntp
